# Permissions:
# sakuraspawners.command.main For using the main command.
# sakuraspawners.command.hitkill For using the secondary command
# sakuraspawners.stack To be able to stack entities with their own egg.
# sakuraspawners.change To enable entity change in a spawner with an egg.

# Modify the name of the Spawner, Egg and Entity.
# You can use {name} to define names automatically.

# When modifying the entity name you can also use:
# {health} current life of the entity.
# {max-health} maximum health of the entity.
# {stack} amount of entities together.
# {max-stack} maximum amount of entities together.

spawner.default.name: '§r§l§d{name} §r§dSpawner'
spawner.default.egg.name: '§r§l§d{name} §r§dEgg'
spawner.default.entity.name: '§r§l§d{name} §r§dx{stack}'

# Here you can define the initial amount of entities together and the maximum amount, 
# if the maximum amount is defined as 1 (one) the entities will not join in a stack.

spawner.default.entity.min.stack: 1
spawner.default.entity.max.stack: 300

# Set the range of the spawn area and the range of the stack area.

spawner.default.entity.spawn.distance: 5
spawner.default.entity.stack.distance: 5

# true = The entity will be knocked back. 
# false = The entity will not be knocked back.

spawner.default.entity.knockback: false

# If you don't know what you're doing, modify as much as possible using the commands!
# Do not modify the lines below using a text editor!

11:
  entity.xp: 1
  entity.drops:
    Item Raw Beef (20175:0)x2: Raw_Beef:2
    Item Leather (20143:0)x1: Leather:1
10:
  entity.xp: 1
  entity.drops:
    Item Feather (20103:0)x1: Feather:1
    Item Raw Chicken (20176:0)x1: Raw_Chicken:1
12:
  entity.xp: 1
  entity.drops:
    Item Raw Porkchop (20179:0)x64: Raw_Porkchop:1
13:
  entity.xp: 1
  entity.drops:
    Item Raw Mutton (20178:0)x64: Raw_Mutton:2
    Item Wool (-10537:14)x64: Wool:1
17:
  entity.xp: 1
  entity.drops:
    Item Ink Sac (20127:0)x64: Ink_Sac:64
20:
  entity.xp: 5
  entity.drops:
    Item Iron Ingot (20133:0)x3: Iron_Ingot:3
    Item Poppy (-10405:0)x64: Poppy:1
32:
  entity.xp: 2
  entity.drops:
    Item Rotten Flesh (20195:0)x64: Rotten_Flesh:2
33:
  entity.xp: 2
  entity.drops:
    Item Gunpowder (20125:0)x64: Gunpowder:1
34:
  entity.xp: 2
  entity.drops:
    Item Arrow (20003:0)x64: Arrow:1
    Item Bone (20016:0)x64: Bone:2
35:
  entity.xp: 2
  entity.drops:
    Item Spider Eye (20201:0)x64: Spider_Eye:1
    Item String (20213:0)x64: String:2
36:
  entity.xp: 3
  entity.drops:
    Item Rotten Flesh (20195:0)x64: Rotten_Flesh:1
    Item Gold Nugget (20113:0)x64: Gold_Nugget:2
37:
  entity.xp: 1
  entity.drops:
    Item Slimeball (20199:0)x64: Slimeball:1
38:
  entity.xp: 3
  entity.drops:
    Item Ender Pearl (20101:0)x16: Ender_Pearl:1
42:
  entity.xp: 2
  entity.drops:
    Item Magma Cream (20148:0)x64: Magma_Cream:1
43:
  entity.xp: 3
  entity.drops:
    Item Blaze Rod (20014:0)x64: Blaze_Rod:1
48:
  entity.xp: 5
  entity.drops:
    Item Nether Star (20158:0)x64: Nether_Star:1